//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 09:38:30 PM IST 
//


package org.nfjs.springws.pcatalog.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetProductResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProductResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProductCategory" type="{http://org.nfjs/springws/pcatalog/response}ProductCategoryType"/&gt;
 *         &lt;element name="ProductsList" type="{http://org.nfjs/springws/pcatalog/response}ProductsListType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProductResponseType", propOrder = {
    "productCategory",
    "productsList"
})
public class GetProductResponseType {

    @XmlElement(name = "ProductCategory", required = true)
    protected String productCategory;
    @XmlElement(name = "ProductsList", required = true)
    protected ProductsListType productsList;

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCategory(String value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the productsList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductsListType }
     *     
     */
    public ProductsListType getProductsList() {
        return productsList;
    }

    /**
     * Sets the value of the productsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductsListType }
     *     
     */
    public void setProductsList(ProductsListType value) {
        this.productsList = value;
    }

}
