//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 09:38:30 PM IST 
//


package org.nfjs.springws.pcatalog.domain.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nfjs.springws.pcatalog.domain.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetProductResponse_QNAME = new QName("http://org.nfjs/springws/pcatalog/response", "GetProductResponse");
    private final static QName _AddProductResponse_QNAME = new QName("http://org.nfjs/springws/pcatalog/response", "AddProductResponse");
    private final static QName _DeleteProductResponse_QNAME = new QName("http://org.nfjs/springws/pcatalog/response", "DeleteProductResponse");
    private final static QName _DefaultResponse_QNAME = new QName("http://org.nfjs/springws/pcatalog/response", "DefaultResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nfjs.springws.pcatalog.domain.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductResponseType }
     * 
     */
    public GetProductResponseType createGetProductResponseType() {
        return new GetProductResponseType();
    }

    /**
     * Create an instance of {@link AddProductResponseType }
     * 
     */
    public AddProductResponseType createAddProductResponseType() {
        return new AddProductResponseType();
    }

    /**
     * Create an instance of {@link DeleteProductResponseType }
     * 
     */
    public DeleteProductResponseType createDeleteProductResponseType() {
        return new DeleteProductResponseType();
    }

    /**
     * Create an instance of {@link DefaultResponseType }
     * 
     */
    public DefaultResponseType createDefaultResponseType() {
        return new DefaultResponseType();
    }

    /**
     * Create an instance of {@link ProductsListType }
     * 
     */
    public ProductsListType createProductsListType() {
        return new ProductsListType();
    }

    /**
     * Create an instance of {@link ProductObjectType }
     * 
     */
    public ProductObjectType createProductObjectType() {
        return new ProductObjectType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.nfjs/springws/pcatalog/response", name = "GetProductResponse")
    public JAXBElement<GetProductResponseType> createGetProductResponse(GetProductResponseType value) {
        return new JAXBElement<GetProductResponseType>(_GetProductResponse_QNAME, GetProductResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddProductResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.nfjs/springws/pcatalog/response", name = "AddProductResponse")
    public JAXBElement<AddProductResponseType> createAddProductResponse(AddProductResponseType value) {
        return new JAXBElement<AddProductResponseType>(_AddProductResponse_QNAME, AddProductResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteProductResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.nfjs/springws/pcatalog/response", name = "DeleteProductResponse")
    public JAXBElement<DeleteProductResponseType> createDeleteProductResponse(DeleteProductResponseType value) {
        return new JAXBElement<DeleteProductResponseType>(_DeleteProductResponse_QNAME, DeleteProductResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefaultResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.nfjs/springws/pcatalog/response", name = "DefaultResponse")
    public JAXBElement<DefaultResponseType> createDefaultResponse(DefaultResponseType value) {
        return new JAXBElement<DefaultResponseType>(_DefaultResponse_QNAME, DefaultResponseType.class, null, value);
    }

}
