//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 09:38:30 PM IST 
//


package org.nfjs.springws.pcatalog.domain.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nfjs.springws.pcatalog.domain.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetProductRequest_QNAME = new QName("http://org.nfjs/springws/pcatalog/request", "GetProductRequest");
    private final static QName _AddProductRequest_QNAME = new QName("http://org.nfjs/springws/pcatalog/request", "AddProductRequest");
    private final static QName _DeleteProductRequest_QNAME = new QName("http://org.nfjs/springws/pcatalog/request", "DeleteProductRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nfjs.springws.pcatalog.domain.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductRequestType }
     * 
     */
    public GetProductRequestType createGetProductRequestType() {
        return new GetProductRequestType();
    }

    /**
     * Create an instance of {@link AddProductRequestType }
     * 
     */
    public AddProductRequestType createAddProductRequestType() {
        return new AddProductRequestType();
    }

    /**
     * Create an instance of {@link DeleteProductRequestType }
     * 
     */
    public DeleteProductRequestType createDeleteProductRequestType() {
        return new DeleteProductRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.nfjs/springws/pcatalog/request", name = "GetProductRequest")
    public JAXBElement<GetProductRequestType> createGetProductRequest(GetProductRequestType value) {
        return new JAXBElement<GetProductRequestType>(_GetProductRequest_QNAME, GetProductRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.nfjs/springws/pcatalog/request", name = "AddProductRequest")
    public JAXBElement<AddProductRequestType> createAddProductRequest(AddProductRequestType value) {
        return new JAXBElement<AddProductRequestType>(_AddProductRequest_QNAME, AddProductRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.nfjs/springws/pcatalog/request", name = "DeleteProductRequest")
    public JAXBElement<DeleteProductRequestType> createDeleteProductRequest(DeleteProductRequestType value) {
        return new JAXBElement<DeleteProductRequestType>(_DeleteProductRequest_QNAME, DeleteProductRequestType.class, null, value);
    }

}
