//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 09:36:41 PM IST 
//


package org.nfjs.springws.productprice.domain.response;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetProductPriceResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProductPriceResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Product" type="{http://org.nfjs/springws/productprice/response}ProductsType"/&gt;
 *         &lt;element name="ProductCategory" type="{http://org.nfjs/springws/productprice/response}ProductCategoryType"/&gt;
 *         &lt;element name="ProductPrice" type="{http://org.nfjs/springws/productprice/response}ProductPriceType"/&gt;
 *         &lt;element name="Currency" type="{http://org.nfjs/springws/productprice/response}CurrencyType"/&gt;
 *         &lt;element name="DiscountOfferMessage" type="{http://org.nfjs/springws/productprice/response}DiscountMessageType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProductPriceResponseType", propOrder = {
    "product",
    "productCategory",
    "productPrice",
    "currency",
    "discountOfferMessage"
})
public class GetProductPriceResponseType {

    @XmlElement(name = "Product", required = true)
    protected String product;
    @XmlElement(name = "ProductCategory", required = true)
    protected String productCategory;
    @XmlElement(name = "ProductPrice", required = true)
    protected BigDecimal productPrice;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "DiscountOfferMessage", required = true)
    protected String discountOfferMessage;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCategory(String value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the productPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * Sets the value of the productPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductPrice(BigDecimal value) {
        this.productPrice = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the discountOfferMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountOfferMessage() {
        return discountOfferMessage;
    }

    /**
     * Sets the value of the discountOfferMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountOfferMessage(String value) {
        this.discountOfferMessage = value;
    }

}
