//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 09:36:41 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://org.nfjs/springws/productprice/response")
package org.nfjs.springws.productprice.domain.response;
